// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePizzaHub.Entities.Models
{
    public partial class Users
    {
        public Users()
        {
            Orders = new HashSet<Orders>();
            PaymentDetails = new HashSet<PaymentDetails>();
            Role = new HashSet<Roles>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public bool EmailConfirmed { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<PaymentDetails> PaymentDetails { get; set; }

        public virtual ICollection<Roles> Role { get; set; }
    }
}